### Testing

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [2]:
z = torch.randn(2, 3, 4)

In [3]:
z.sum(dim=(1,)).shape

torch.Size([2, 4])

In [4]:
len(z.shape)

3

In [5]:
[i for i in range(2, len(z.shape))]

[2]

In [6]:
z

tensor([[[ 0.3403, -0.0996,  0.8317,  0.0292],
         [ 0.2502,  0.5125,  0.2854,  0.1968],
         [-1.0844, -0.1888, -0.3405, -0.6832]],

        [[-0.1299, -0.6610,  1.0111, -0.4988],
         [-0.3281, -0.0127, -0.4559, -1.0405],
         [ 0.3418,  0.6893,  0.8568,  0.3378]]])

In [7]:
torch.round(z).unique()

tensor([-1.,  0.,  1.])

In [8]:
~np.array([1,0,1,0])

array([-2, -1, -2, -1])

In [9]:
~torch.Tensor([1,0,1,0]).type(torch.bool)

tensor([False,  True, False,  True])

In [10]:
torch.logical_not

<function torch._VariableFunctionsClass.logical_not>

In [11]:
result = torch.meshgrid(torch.arange(0,5,1), torch.arange(0,6,1), torch.arange(0,7,1))

/home/benp/anaconda3/envs/loss/lib/python3.9/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


In [12]:
torch.stack(result).shape

torch.Size([3, 5, 6, 7])

In [13]:
a = torch.randn(2, 2, 3)
b = torch.randn(2,3)

In [14]:
(a + b).shape

torch.Size([2, 2, 3])

In [15]:
a[1] + b

tensor([[ 0.2520, -0.1863, -0.2478],
        [ 1.2881, -0.2275,  0.2608]])

In [16]:
(a+b)[1]

tensor([[ 0.2520, -0.1863, -0.2478],
        [ 1.2881, -0.2275,  0.2608]])

In [17]:
spatial_dims = [25, 25, 25]
grid = torch.stack(
            torch.meshgrid(
                *[torch.arange(0, sdi, 1) for sdi in spatial_dims],
                indexing='ij'
            )
        )

In [18]:
torch.cartesian_prod(*[torch.arange(0, sdi, 1) for sdi in spatial_dims]).shape

torch.Size([15625, 3])

In [19]:
grid.shape

torch.Size([3, 25, 25, 25])

In [20]:
example_mask = torch.zeros(spatial_dims)

In [21]:
example_mask[10:15+1, 7:10+1, 20:22+1] = 1

In [22]:
grid[:,example_mask.type(torch.bool)].type(torch.float32).mean(dim=1)

tensor([12.5000,  8.5000, 21.0000])

In [24]:
torch.Tensor([*grid.shape[2:]]).prod()

tensor(625.)

In [25]:
z = torch.randn((10,10)) * 10

In [26]:
z.tanh()

tensor([[ 0.9974, -0.9997, -1.0000, -1.0000,  1.0000, -1.0000,  1.0000, -1.0000,
         -1.0000,  1.0000],
        [ 1.0000, -1.0000, -0.9934, -0.9955, -1.0000, -1.0000,  1.0000, -1.0000,
          1.0000,  0.9995],
        [-1.0000, -0.9991, -1.0000,  1.0000,  1.0000, -0.9838,  1.0000, -0.8277,
          1.0000, -1.0000],
        [ 1.0000, -0.9999, -1.0000,  0.6091, -1.0000,  0.5371, -0.9785, -0.9924,
          1.0000,  0.9636],
        [-1.0000,  1.0000, -1.0000,  1.0000, -1.0000, -1.0000, -0.9899, -0.9999,
          0.1476,  1.0000],
        [ 0.4363, -0.6139, -1.0000, -0.8547,  1.0000, -0.9998, -1.0000, -1.0000,
          1.0000,  1.0000],
        [-0.9053,  1.0000, -0.9999,  1.0000, -1.0000, -1.0000,  1.0000,  1.0000,
         -1.0000, -0.9853],
        [-0.9997,  0.9998,  1.0000, -1.0000, -1.0000,  1.0000, -0.8853, -1.0000,
         -1.0000, -0.0730],
        [-1.0000, -0.9996,  1.0000, -1.0000, -1.0000, -1.0000, -0.9013, -0.9918,
          1.0000, -1.0000],
        [-0.9950,  